project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
    path('recipes/category/<int:category_id>/',
         views.category, name='category'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL,
        null=True, blank=True, default=None)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title


# EDITED
# title description slug
# preparation_time preparation_time_unit
# servings servings_unit
# preparation_step
# preparation_step_is_html
# created_at updated_at
# is_published
# cover
# category (Relação)
# Author (Relação)

recipes/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Recipe


def home(req):
    return render(req, 'recipes/pages/home.html', context={
        'recipes': Recipe.objects.filter(
            is_published=True
        ).order_by('-id')
    })


def category(req, category_id):

    recipes = Recipe.objects.filter(
        category__id=category_id,
        is_published=True
    ).order_by('-id')

    if not recipes:
        return HttpResponse('Not Found', status=404)

    return render(req, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes.first().category.name} | Category'
    })


def recipe(req, id):

    recipe = Recipe.objects.filter(
        id=id,
        is_published=True,
    ).order_by('-id').first()

    if not recipe:
        return HttpResponse('Nenhuma receita encontrada!', status=404)

    return render(req, 'recipes/pages/recipes-view.html', context={
        'is_recipe_page': True,
        'recipe': recipe
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}
    {{ title }}
{% endblock title %}


{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}


</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}


</div>
{% endblock content %}

recipes/templates/recipes/pages/recipes-view.html
{% extends 'global/base.html' %}

{% block title %}
    Recipe
{% endblock title %}

{% block content %}
<div class="main-content main-content-details container">
    {% include 'recipes/partials/recipe.html' %}            
</div>
{% endblock content %}

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static '/recipes/css/style.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href=" {% url 'recipes:home' %} ">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href=" {% url 'recipes:recipe' recipe.id %} ">
            <img src="{{ recipe.cover.url }}">
        </a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name and recipe.author.last_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}

        </span>
        {% if recipe.author %}
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
            </span>
        {% endif %}

        {% if recipe.category %}
        
        {% if is_recipe_page is not True %}<br><br>{% endif %}
        <span class="recipe-author-item">
            <a href=" {% url 'recipes:category' recipe.category.id %} ">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_recipe_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_recipe_page %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
            {{ recipe.preparation_steps|safe }}
        {% else %}
            {{ recipe.preparation_steps|linebreaksbr }}
        {% endif %}
        </div>
    {% endif %}



</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>